# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# [[ -z $DISPLAY && $(tty) == /dev/tty1 ]] && exec Hyprland

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export JULIA_PKG_PRESERVE_TIERED_INSTALLED=true
# export CC="musl-clang"
#export CC="musl-clang -fuse-ld=musl-clang"
export CC=clang 
export CXX=clang++
#export CC=clang
#export CXX=clang

#--------------- XDG Base Directory ---------------
#----- User directories
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=/run/user/$UID
#----- System directories
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg
#----- Fixes for programs
# Rust & Cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo
# Golang
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
# Docker & docker-machine
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine
# FFMPEG
export FFMPEG_DATADIR="$XDG_CONFIG_HOME"/ffmpeg
# coreutils
# eval $(dircolors "$XDG_CONFIG_HOME"/dircolors)
# CUDA
# export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
#--------------------------------------------------

# ZSH_THEME="clean"
ZSH_THEME="gentoo"

DISABLE_AUTO_UPDATE=true

plugins=(git cp colorize rsync zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

alias l="exa -l -a"
alias pm="sudo pacman"
